from django.db import models

# Create your models here.

class Organization(models.Model):
    yearcode = models.IntegerField(blank=True)
    periodcode = models.IntegerField(blank=True)
    inn = models.CharField(max_length=1000, blank=True)
    ogrn = models.CharField(max_length=1000, blank=True)
    regionname = models.CharField(max_length=1000, blank=True)
    namep = models.CharField(max_length=1000, blank=True)
    namec = models.CharField(max_length=1000, blank=True)
    invalid = models.BooleanField(blank=True)
    okved2 = models.CharField(max_length=1000, blank=True)
    okved2name = models.CharField(max_length=1000, blank=True)
    token = models.CharField(max_length=1000, blank=True)
    kpprafp = models.CharField(max_length=1000, blank=True)
    is_protch_przd = models.BooleanField(blank=True)
    foreignorg = models.BooleanField(blank=True)
    okopf12 = models.CharField(max_length=1000, blank=True)
    pr_otch = models.CharField(max_length=1000, blank=True)
    pr_otch_zd_date = models.CharField(max_length=1000, blank=True)
    pr_rafp = models.CharField(max_length=1000, blank=True)
    pr_zd = models.CharField(max_length=1000, blank=True)
    rsmpcategory = models.CharField(max_length=1000, blank=True)
    address = models.CharField(max_length=1000, blank=True)
    date_vyp = models.CharField(max_length=1000, blank=True)
    date_entry = models.CharField(max_length=1000, blank=True)
    date_ogrn = models.CharField(max_length=1000, blank=True)
    date_post = models.CharField(max_length=1000, blank=True)
    date_reg = models.CharField(max_length=1000, blank=True)
    build = models.CharField(max_length=1000, blank=True)
    post_index = models.CharField(max_length=1000, blank=True)
    kpp = models.CharField(max_length=1000, blank=True)
    kod_no = models.CharField(max_length=1000, blank=True)
    kod_okved = models.CharField(max_length=1000, blank=True)
    kod_ro = models.CharField(max_length=1000, blank=True)
    kod_region = models.CharField(max_length=1000, blank=True)
    corpus = models.CharField(max_length=1000, blank=True)
    tax_dept_name = models.CharField(max_length=1000, blank=True)
    main_okved_name = models.CharField(max_length=1000, blank=True)
    tax_dept_name_main = models.CharField(max_length=1000, blank=True)
    ul_reg_method = models.CharField(max_length=1000, blank=True)
    ul_street = models.CharField(max_length=1000, blank=True)
    # ul_full_name: "\"АССОЦИАЦИЯ НАУЧНЫХ И УЧЕБНЫХ ОРГАНИЗАЦИЙ - ПОЛЬЗОВАТЕЛЕЙ ЭЛЕКТРОННЫХ СЕТЕЙ ПЕРЕДАЧИ ДАННЫХ \"РЕЛАРН\""
    # ul_short_name: "АССОЦИАЦИЯ \"РЕЛАРН\""
    ogrn = models.CharField(max_length=1000, blank=True)
    region_type = models.CharField(max_length=1000, blank=True)
    street_type = models.CharField(max_length=1000, blank=True)
    other_data = models.JSONField(blank=True, default=None, null=True)