# Generated by Django 3.2.9 on 2021-11-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearcode', models.IntegerField(blank=True)),
                ('periodcode', models.IntegerField(blank=True)),
                ('inn', models.CharField(blank=True, max_length=1000)),
                ('regionname', models.CharField(blank=True, max_length=1000)),
                ('namep', models.CharField(blank=True, max_length=1000)),
                ('namec', models.CharField(blank=True, max_length=1000)),
                ('invalid', models.BooleanField(blank=True)),
                ('okved2', models.CharField(blank=True, max_length=1000)),
                ('okved2name', models.CharField(blank=True, max_length=1000)),
                ('token', models.CharField(blank=True, max_length=1000)),
                ('kpprafp', models.CharField(blank=True, max_length=1000)),
                ('is_protch_przd', models.BooleanField(blank=True)),
                ('foreignorg', models.BooleanField(blank=True)),
                ('okopf12', models.CharField(blank=True, max_length=1000)),
                ('pr_otch', models.CharField(blank=True, max_length=1000)),
                ('pr_otch_zd_date', models.CharField(blank=True, max_length=1000)),
                ('pr_rafp', models.CharField(blank=True, max_length=1000)),
                ('pr_zd', models.CharField(blank=True, max_length=1000)),
                ('rsmpcategory', models.CharField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('date_vyp', models.CharField(blank=True, max_length=1000)),
                ('date_entry', models.CharField(blank=True, max_length=1000)),
                ('date_ogrn', models.CharField(blank=True, max_length=1000)),
                ('date_post', models.CharField(blank=True, max_length=1000)),
                ('date_reg', models.CharField(blank=True, max_length=1000)),
                ('build', models.CharField(blank=True, max_length=1000)),
                ('post_index', models.CharField(blank=True, max_length=1000)),
                ('kpp', models.CharField(blank=True, max_length=1000)),
                ('kod_no', models.CharField(blank=True, max_length=1000)),
                ('kod_okved', models.CharField(blank=True, max_length=1000)),
                ('kod_ro', models.CharField(blank=True, max_length=1000)),
                ('kod_region', models.CharField(blank=True, max_length=1000)),
                ('corpus', models.CharField(blank=True, max_length=1000)),
                ('tax_dept_name', models.CharField(blank=True, max_length=1000)),
                ('main_okved_name', models.CharField(blank=True, max_length=1000)),
                ('tax_dept_name_main', models.CharField(blank=True, max_length=1000)),
                ('ul_reg_method', models.CharField(blank=True, max_length=1000)),
                ('ul_street', models.CharField(blank=True, max_length=1000)),
                ('ogrn', models.CharField(blank=True, max_length=1000)),
                ('region_type', models.CharField(blank=True, max_length=1000)),
                ('street_type', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
