# Generated by Django 3.2.9 on 2021-11-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='other_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
